LBHackney-IT/single-view-frontend

apps/single-view/src/Components/Input.tsx, apps/single-view/src/Components/index.tsx, apps/single-view/src/Views/SearchView/searchByResident.tsx, cypress/integration/2-search.spec.ts
Adding error messages on input fields
=> refactor input fields to use a component and add error messages

apps/single-view/.env.sample, apps/single-view/src/Views/SearchView/searchResults.tsx
https://trello.com/c/fQcneCGl/132-%F0%9F%90%9B-some-users-with-no-dob-shows-us-as-being-born-in-01-01-1900
=> Fixes DoB bug 

apps/single-view/.env.sample, apps/single-view/src/Components/NoteInput.tsx, apps/single-view/src/Gateways/Notes.test.tsx, apps/single-view/src/Gateways/Notes.tsx, apps/single-view/src/Interfaces/index.tsx, apps/single-view/src/Interfaces/systemIdInterface.tsx, apps/single-view/src/Views/CustomerView/Notes.tsx, apps/single-view/src/Views/CustomerView/index.tsx, apps/single-view/webpack.config.js
https://trello.com/c/SzvS2SmK/110-refactor-front-end-to-use-sv-api-for-notes
- Remove NOTES_API_V2 references
- Refactor notes gateway
- Move notes API calls into the notes view
- Add API error handling to the notes components
=> Use SingleViewApi for notes

.circleci/config.yml, apps/single-view/.env.sample, apps/single-view/src/Gateways/SearchResident.tsx, apps/single-view/src/Views/CustomerView/index.tsx, apps/single-view/webpack.config.js
**Env vars have been set on all envs**
=> add link to mmh

apps/single-view/src/Views/CustomerView/Notes.tsx, apps/single-view/src/Views/CustomerView/index.tsx, apps/single-view/src/Views/SearchView/searchByResident.tsx, apps/single-view/src/app.scss
https://trello.com/c/lAhPhSbm/160-tech-debt-loading-spinner-remove-add-note-option-for-jigsaw
=> Loading Spinner & Remove Add Notes Option For Jigsaw

apps/single-view/src/Components/Alert.tsx, apps/single-view/src/Interfaces/CautionaryAlertInterfaces.tsx, apps/single-view/src/Interfaces/customerProfileInterfaces.tsx, apps/single-view/src/Utils/formatDates.test.tsx, apps/single-view/src/Utils/formatDates.tsx, apps/single-view/src/Views/CustomerView/Profile.tsx, apps/single-view/src/app.scss, cypress/fixtures/person-profile.json, cypress/integration/4-profile.spec.ts
https://trello.com/c/5SZECgH8/205-integrated-with-cautionary-alerts-api
=> Add Alert component to show cautionary alerts on person profile page

apps/single-view/src/Views/CustomerView/Profile.tsx, apps/single-view/src/Views/CustomerView/index.tsx, cypress/integration/4-profile.spec.ts
Co-authored-by: Charli Wild <charli.wild@madetech.com>
Co-authored-by: Adam Tracy <adam.tracy@hackney.gov.uk>
=> display system Ids to profile 

apps/single-view/src/Components/EqualityInformation.tsx, apps/single-view/src/Interfaces/customerProfileInterfaces.tsx, apps/single-view/src/Interfaces/equalityInformationInterfaces.tsx, apps/single-view/src/Views/CustomerView/Profile.tsx, cypress/fixtures/person-profile.json, cypress/integration/4-profile.spec.ts
https://trello.com/c/kcdG4WiY/240-restore-equality-information
=> Add equality information on profile page

apps/header/src/app.tsx, apps/header/src/services/locale.ts
Added a link to the new support form to the banner
Added a link to the Pilot google chat to the banner
=> Update the banner to add support form and google chat

apps/single-view/src/Components/SearchResultsGroup.tsx, apps/single-view/src/Components/UnmergeRecordButton.tsx, apps/single-view/src/Gateways/recordsGateway.test.tsx, apps/single-view/src/Gateways/recordsGateway.tsx, apps/single-view/src/Views/SearchView/searchResults.tsx, apps/single-view/src/app.scss
Allows users to unmerge incorrectly merged SV records
=> Unmerge records

apps/single-view/src/Components/SearchResultsGroup.tsx, apps/single-view/src/Utils/humanize.tsx, apps/single-view/src/app.scss, cypress/fixtures/person-cases.json, cypress/integration/2-search.spec.ts, cypress/integration/3-match.spec.js
Shows which records are merged and which systems the data for the records comes from in the search results.
Needs some API work to send the NI Numbers through to the search results, and ideally to send a list of IDs or systems for the merged results so that the frontend can display that.
=> Display merge status in the search results

apps/single-view/src/Interfaces/customerProfileInterfaces.tsx, apps/single-view/src/Views/CustomerView/Profile.tsx, cypress/fixtures/person-profile.json, cypress/integration/4-profile.spec.ts
Related to: https://github.com/LBHackney-IT/single-view-api/pull/88
- updates keys and cypress tests
=> updated keys and cypress

.circleci/config.yml, apps/single-view/.env.sample, apps/single-view/src/Components/HousingBenefitsInformation.tsx, apps/single-view/src/Views/CustomerView/index.tsx, apps/single-view/webpack.config.js, cypress/integration/8-backToSearch.spec.ts
**Rename household composition title**
**Add view-on-jigsaw link on profile page**
=> Rename household composition title, add view-on-jigsaw link

apps/single-view/src/Components/HousingBenefitsInformation.tsx, apps/single-view/src/Interfaces/housingBenefitsRecordInterfaces.tsx
=> added field for whba

apps/single-view/src/Components/BackToSearch.tsx, apps/single-view/src/Views/CustomerView/index.tsx, cypress/integration/8-backToSearch.spec.ts
https://trello.com/c/IOrrU69p/332-clear-search-button
=> Add new search link

apps/root/src/index.ejs
https://trello.com/c/qFCmTrl2/318-tracking-code-for-single-view-universal-analytics
- Added a tracking script for Single View Universal Analytics
=> Add tracking script for Single View Universal Analytics

cypress/integration/6-notes.spec.ts
**What was the issue?**
The notes were not loading in cypress as cypress wasn't intercepting with jigsaw cookie. 
**What changes are introduced?**
Implemented code to intercept and apply required changes before each test.
=> Fix interception issue

apps/single-view/src/Views/SearchView/searchByResident.tsx
https://user-images.githubusercontent.com/31739633/186697615-580de137-d70d-4d5a-88da-4ead3b4eea10.mov
=> Fix the search residents spinner to animate as results are being loaded

apps/single-view/src/Components/HousingBenefitsInformation.tsx, apps/single-view/src/Interfaces/housingBenefitsRecordInterfaces.tsx, cypress/fixtures/person-profile.json, cypress/integration/4-profile.spec.ts
=> Add landlord details on profile page

apps/single-view/src/Components/HousingBenefitsInformation.tsx, apps/single-view/src/Interfaces/housingBenefitsRecordInterfaces.tsx, apps/single-view/src/Utils/formatDates.tsx
=> Last payment details

apps/header/src/app.tsx, apps/header/src/services/locale.ts, cypress/integration/2-search.spec.ts, cypress/integration/3-match.spec.ts, cypress/integration/4-profile.spec.ts, cypress/integration/5-jigsawLoginLogout.spec.ts, cypress/integration/6-notes.spec.ts, cypress/integration/7-cases.spec.ts, cypress/integration/8-backToSearch.spec.ts, cypress/pages/base/base-person-page.ts
Updated the header links and banner tag
Updated cypress tests to intercept before visiting - more reliable
=> Updated the header links and banner tag

apps/auth/src/services/locale.ts, apps/auth/src/views/login-view/login-view.tsx
Now setting auth link in the auth/services/locale.ts file and using it in the custom login function in auth/views/login-view/login-view.tsx
=> Set auth link in config instead of as env variable

README.md, apps/auth/src/root.component.spec.tsx, package.json, yarn.lock
Attempted to fix dev deployment by removing dependence on new environment variables.
=> Concurrently updated and added requirement to README.md

apps/auth/webpack.config.js
Should resolve CircleCI auth build failure
=> Removed webpack EnvironmentPlugin for AUTH_DOMAIN

apps/auth/src/views/login-view/login-view.tsx, apps/common/lib/auth/auth.ts, apps/header/src/app.tsx, apps/single-view/src/Config/locale.ts, apps/single-view/src/Views/CustomerView/Cases.tsx, apps/single-view/src/Views/CustomerView/Notes.tsx, apps/single-view/src/Views/CustomerView/index.tsx, apps/single-view/src/Views/JigsawLogin/index.tsx, apps/single-view/src/Views/SearchView/index.tsx, cypress/integration/3-match.spec.ts, cypress/pages/search-page.ts, cypress/support/commands.ts, package.json, yarn.lock
Configure titles in `/single-view/src/Config/locale.ts`
Titles are set based on this config in each view file in `/single-view/src/Views`
Titles are set together in the `index.ts` of `Views/CustomerView`
=> Set titles for pages

apps/root/src/index.ejs
Checks for single view production URL to add tag
=> Only add Google Analytics tag if running in production

apps/single-view/src/Components/JigsawLogin.tsx, apps/single-view/src/Views/CustomerView/index.tsx, apps/single-view/src/Views/JigsawLogin/index.tsx, apps/single-view/src/Views/SearchView/index.tsx, apps/single-view/src/app.tsx, cypress/integration/5-jigsawLoginLogout.spec.ts
Fixes JigsawLogin redirect and may help with GA data accuracy for pages
=> useEffect for page title setting

.circleci/config.yml, apps/single-view/src/Views/SearchView/searchByResident.tsx, apps/single-view/src/Views/SearchView/searchResults.tsx, cypress/integration/2-search.spec.ts, cypress/integration/3-match.spec.ts, cypress/pages/search-page.ts, package.json
[Trello Card](https://trello.com/c/62K4UYM1/13-clear-search-button)
New button in searchResults
Added IDs to buttons on search page
=> Added clear search functionality

apps/auth/src/services/locale.ts, apps/auth/src/views/login-view/login-view.tsx
[Trello card](https://trello.com/c/b6Tlm8ua/10-advise-users-to-clear-chrome-cache-and-cookies-in-case-they-fail-to-log-in-or-dont-see-the-login-page)
=> Provided advice for login failures

apps/single-view/src/Views/SearchView/searchByResident.tsx, cypress/integration/2-search.spec.ts
Clear search button and search button only displayed when there is data in the search fields - should help to reduce confusion or user error selecting buttons.
=> Clear search button
